{{- if .Values.ldap.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: uaa-ldap
  labels:
    {{- include "uaa-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 389
      targetPort: 389
      protocol: TCP
      name: ldap
    - port: 636
      targetPort: 636
      protocol: TCP
      name: ldap-tls
  selector:
    app: ldap
{{- end }}