---
apiVersion: v1
kind: Secret
metadata:
  name: uaa-admin-client-credentials
type: Opaque
stringData:
  admin_client_credentials.yml: |
    oauth:
      clients:
        admin:
          secret: {{- randAlphaNum 20 | indent 1 }}